version: 0.2
phases:
    install:
      runtime-versions:
        python: 3.11
      commands:
        - echo "Installing dependencies..."
        - pip install -r requirements.txt -t lib
    build:
      commands:
        - echo "zipping deployment package"
        - cd lib
        - zip -r9 ../deployment_package.zip .
        - cd ..
        - zip -g deployment_package.zip  lambda_function.py
    post-build:
      commands:
        - echo "uploading to s3"
        - aws s3 cp deployment_package.zip s3://lambda-builds-zip-demo-test/
        - echo "updating lambda function va s3"
        - aws lambda update-function-code --function-name github-test --s3-bucket lambda-builds-zip-demo-test --s3-key deployment_package.zip
        - echo "deployment complete"